-- Add missing columns to tests table
ALTER TABLE tests 
ADD COLUMN IF NOT EXISTS status text DEFAULT 'active';

ALTER TABLE tests 
ADD COLUMN IF NOT EXISTS ai_evaluation_enabled boolean DEFAULT false;

ALTER TABLE tests 
ADD COLUMN IF NOT EXISTS is_ai_generated boolean DEFAULT false;

-- Add comments
COMMENT ON COLUMN tests.status IS 'Test status: active, inactive, archived';
COMMENT ON COLUMN tests.ai_evaluation_enabled IS 'Whether AI evaluation is enabled for this test';
COMMENT ON COLUMN tests.is_ai_generated IS 'Whether this test was generated by AI';
