-- Run this in your Supabase SQL Editor to add proper AI test support

-- Step 1: Add ai_generated to the test_type constraint
ALTER TABLE tests DROP CONSTRAINT IF EXISTS tests_test_type_check;
ALTER TABLE tests ADD CONSTRAINT tests_test_type_check 
  CHECK (test_type IN ('mcq', 'coding', 'essay', 'case_study', 'mixed', 'ai_generated'));

-- Step 2: Add a column to explicitly track AI generation (optional, for better organization)
ALTER TABLE tests ADD COLUMN IF NOT EXISTS is_ai_generated boolean DEFAULT false;

-- Step 3: Add an index for better performance when filtering AI tests
CREATE INDEX IF NOT EXISTS idx_tests_ai_generated ON tests(is_ai_generated);

-- Step 4: Update column comments for clarity
COMMENT ON COLUMN tests.is_ai_generated IS 'Indicates if this test was generated by AI based on job requirements';
COMMENT ON COLUMN tests.test_type IS 'Type of test: mcq, coding, essay, case_study, mixed, or ai_generated';

-- Step 5: (Optional) Update existing tests that might be AI-generated
-- UPDATE tests SET is_ai_generated = true WHERE description LIKE '%AI Generated%';

-- Verify the changes
SELECT 
  column_name, 
  data_type, 
  is_nullable, 
  column_default
FROM information_schema.columns 
WHERE table_name = 'tests' 
  AND table_schema = 'public'
  AND column_name IN ('test_type', 'is_ai_generated');